//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChugenTocc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeToccTable
    {
        public int Id { get; set; }
        public string Departmen { get; set; }
        public string EmployeeNumber { get; set; }
        public string Name { get; set; }
        public string Time { get; set; }
        public string Crowd { get; set; }
        public string Place { get; set; }
        public string Temperature { get; set; }
        public string Symptom { get; set; }
    }
}
