//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChujenTocc2.ChugenTocc.ChugenTocc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHR
    {
        public int id { get; set; }
        public string EmpNumber { get; set; }
        public string EmpName { get; set; }
        public string EmpDepart { get; set; }
    }
}
