//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChujenTocc2.ChugenTocc.ChugenTocc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public string Dept { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string EnrollID { get; set; }
        public string Date { get; set; }
        public string Min { get; set; }
        public string Mout { get; set; }
        public string Ain { get; set; }
        public string Aout { get; set; }
        public string TimeRecord { get; set; }
        public string Cheked { get; set; }
        public string Marking { get; set; }
        public int @int { get; set; }
    }
}
