//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChujenTocc2.ChugenTocc.ChugenTocc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RH2
    {
        public int id { get; set; }
        public Nullable<double> PNumber { get; set; }
        public Nullable<double> Number { get; set; }
        public string Name { get; set; }
        public string LDate { get; set; }
        public string ODate { get; set; }
        public string Division { get; set; }
        public string IDcard { get; set; }
        public string Codename { get; set; }
        public string OrderDoctor { get; set; }
        public string Morder { get; set; }
        public string MorderName { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Count { get; set; }
        public Nullable<double> Money { get; set; }
    }
}
